<?php
// $Id$
// $Name$

function pift_client_install() {
  drupal_set_message(t('The Project issue file test client module was installed successfully.'));
}

function pift_client_uninstall() {
  $vars = array(
    'pift_client_sites',
    'pift_client_testing_file',
  );

  foreach ($vars as $var) {
    variable_del($var);
  }

  drupal_set_message(t('The Project issue file test client module was uninstalled successfully.'));
}